name: binder
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - mdanalysis
  - ipython
  - nglview
  - ipywidgets=7.6.0
  - pip:
    - poreana
    - porems
    - pandas
    - matplotlib