name: binder
channels:
  - conda-forge

dependencies:
  - python>=3.8
  - pip
  - ipython
  - ipywidgets==7.*   
  - matplotlib
  - mdanalysis
  - mdanalysistests
  - mdanalysisdata
  - nglview
  - pip:
    - poreana
    - porems
    - pandas

