name: binder
channels:
  - conda-forge

dependencies:
  - python>=3.6
  - pip
  - pytest
  - jupyterlab
  - nodejs
  - yarn
  - ipython
  - ipywidgets==7.*   
  - matplotlib
  - mdanalysis
  - mdanalysistests
  - mdanalysisdata
  - nglview
  - pip:
    - poreana
    - porems
    - pandas
    - matplotlib
