name: binder
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pip
  #- ipython
  #- ipywidgets    
  - matplotlib
  - mdanalysis>=1.1.1
  - mdanalysistests>=1.1.1
  - mdanalysisdata
  - nglview
  - pip:
    - poreana
    - porems
    - pandas
    - matplotlib